# Generated by Django 4.2.13 on 2024-06-05 19:30

import avaliacao.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Db_Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_limite', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Enviado', 'Enviado'), ('Publicado', 'Publicado')], default=('Pendente', 'Pendente'), max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Db_Criterios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=6, null=True)),
                ('criterio', models.TextField(null=True)),
                ('recurso', models.CharField(max_length=25, null=True)),
                ('dimensao', models.CharField(max_length=30, null=True)),
                ('periodicidade', models.CharField(choices=[('Mensal', 'Mensal'), ('Bimestral', 'Bimestral'), ('Trimestral', 'Trimestral'), ('Quadrimestral', 'Quadrimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual'), ('Tempestivo', 'Tempestivo')], max_length=20, null=True)),
                ('responsavel', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Db_Avaliacao_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=avaliacao.models.diretorioItemAvaliacao)),
                ('anotacao', models.TextField(blank=True, null=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao.db_avaliacao')),
            ],
        ),
        migrations.AddField(
            model_name='db_avaliacao',
            name='criterio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avaliacao.db_criterios'),
        ),
    ]
