# Generated by Django 4.2.13 on 2024-06-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0002_alter_db_criterios_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_avaliacao_log',
            name='dataehora',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
