# Generated by Django 4.2.13 on 2024-06-08 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0005_alter_db_criterios_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Db_dimensao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensao', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='db_criterios',
            name='recurso',
        ),
        migrations.AlterField(
            model_name='db_criterios',
            name='dimensao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='avaliacao.db_dimensao'),
        ),
    ]
