# Generated by Django 4.2.13 on 2024-06-08 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('avaliacao', '0006_db_dimensao_remove_db_criterios_recurso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_criterios',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='db_avaliacao',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
        ),
    ]
